# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57adf9e16cf491fc7b6938f264a5a852fcb60018d975e837109e5192be6bd77ff01cdce697ad3245c5150025c6096ff075392ec9bba7c8925559d71f5902cedd

test:
  secret_key_base: fa3357198e04b03d7aeb62dbc043a31f6dd7667c6bef3cc8ca232148eb82a1fbc6d088324f4c3356d75aff8f746f52d020b6942924238b7e17cf24e61dd02784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
